### ISSUE TITLE
where is the paper?

### ISSUE THREAD

**Issue by mikewin** [nbfigueroa/SPCM-CRP#1]
Not find it in Arxiv, please give a link.

Thanks!

**Comment by mikewin** [comment]
BTW:
 when use demo_clust_spcmCRT.m  try  Toy 6D dataset, alway get 1 cluster
*** Initialized with 60 clusters out of 60 observations ***
Running dd-CRP Mixture Sampler... 
Iteration 1: Started with 60 clusters --> moved to 14 clusters with logprob = -420.90
Iteration 2: Started with 14 clusters --> moved to 2 clusters with logprob = -252.99
Iteration 3: Started with 2 clusters --> moved to 1 clusters with logprob = -249.44
Iteration 4: Started with 1 clusters --> moved to 1 clusters with logprob = -236.22
Iteration 5: Started with 1 clusters --> moved to 1 clusters with logprob = -250.53
Iteration 6: Started with 1 clusters --> moved to 1 clusters with logprob = -248.69
Iteration 7: Started with 1 clusters --> moved to 1 clusters with logprob = -258.81
Iteration 8: Started with 1 clusters --> moved to 1 clusters with logprob = -246.23
Iteration 9: Started with 1 clusters --> moved to 1 clusters with logprob = -252.17
Iteration 10: Started with 1 clusters --> moved to 1 clusters with logprob = -244.48
Iteration 11: Started with 1 clusters --> moved to 1 clusters with logprob = -249.32
Iteration 12: Started with 1 clusters --> moved to 1 clusters with logprob = -250.45
Iteration 13: Started with 1 clusters --> moved to 1 clusters with logprob = -256.74
Iteration 14: Started with 1 clusters --> moved to 1 clusters with logprob = -243.37
Iteration 15: Started with 1 clusters --> moved to 1 clusters with logprob = -245.61
Iteration 16: Started with 1 clusters --> moved to 1 clusters with logprob = -251.58
Iteration 17: Started with 1 clusters --> moved to 1 clusters with logprob = -251.23
Iteration 18: Started with 1 clusters --> moved to 1 clusters with logprob = -246.88
Iteration 19: Started with 1 clusters --> moved to 1 clusters with logprob = -246.95
Iteration 20: Started with 1 clusters --> moved to 1 clusters with logprob = -243.48

 all parameters are not changed.

**Comment by sinamr88** [comment]
You can find the paper here:
https://arxiv.org/abs/1710.10060
